config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'blogs', to: 'pages#blogs'

  post 'message', to: 'messages#create', as: 'new_message'

  resources :sitemaps, :only => :show
  get "sitemap" => "sitemaps#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  module ActiveModel::Validations::HelperMethods
    def validates_email(*attr_names)
      validates_with EmailValidator, _merge_attributes(attr_names)
    end
  end

  include ActiveModel::Model
  include ActiveModel::Validations
  attr_accessor :name, :email, :date, :phone_number, :body
  validates :name, :email, :phone_number, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
invisible_captcha only: [:create ], honeypot: :address
  def create
    @message = Message.new message_params
    # if @message.valid? && verify_recaptcha!(model: @message)
      if @message.valid?
      MessageMailer.email_contact(@message).deliver_now
      MessageMailer.email_enquiry(@message).deliver_now
      flash[:notice] = "Thank you! I will be in touch soon!"
      redirect_to root_path
    else
      flash[:alert] = "There was an error sending your message. Please try again."
      redirect_to root_path
    end
  end
  private
  def message_params
    params.require(:message).permit(:name, :email, :phone_number, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def blogs
    # require "rss"
    # require 'open-uri'
    # rss_results = []
    # rss = RSS::Parser.parse(open("http://medium.com/feed/@rshotton?format=xml").read, false).items
    # rss.each do |result|
    #   image = result.content_encoded.to_s.html_safe.match(/http([\w\W]+?)(jpeg|gif|jpg|png|tiff|JPEG|JPG|TIFF|PNG)/)
    #   description = result.content_encoded.to_s.html_safe.gsub(/<figure>([\w\W]+?)<\/figure>/, '')
    #   result = { title: result.title, date: result.pubDate, link: result.link, description: result.description, content: description, image: image }
    #   rss_results.push(result)
    # end
    # @blogs = rss_results
  end

end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def show
    respond_to do |format|
     format.xml
   end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :message
  end

  def resource
    @resource ||= Message.new
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-WBF0XTG8GV"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-WBF0XTG8GV');
    </script>
    <title>Paul Craven - Behavioural Economics Expert Speaker</title>
    <link rel="canonical" href="https://www.paulcraven.com/">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta property="og:image" content=<%= image_url("pc-og.png") %>>
    <meta property="og:url" content="https://www.paulcraven.com">
    <meta property="og:title" content="Paul Craven Partners Ltd">
    <meta property="og:type" content="website" />
    <meta property="og:description" content="World renowned behavioural science speaker, Paul Craven gives fascinating and insightful talks around investment, sales and business">
    <meta property="og:site_name" content="Paul Craven - Behavioural Economics Expert" />
    <!-- ADD METATAGS -->
    <meta name="description" content="World renowned behavioural science speaker, Paul Craven gives fascinating and insightful talks around investment, sales and business">
    <meta name="keywords" content="speaker, keynote speaker, behavioural economics expert, behavioural economics, expert speaker, master of ceromonies, paul craven, goldman sachs, schroders, tedx talk, ted talk, rory sutherland, ogilvy, nudgestock, investments, magic, magician, psychology, decision making, election campaigns,">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="content-language" content="en" />
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "Paul Craven",
        "url": "http://www.paulcraven.com",
        "sameAs": [
        "https://www.facebook.com/paulcravenpartners/",
        "https://twitter.com/cravenpartners",
        "https://www.linkedin.com/in/paul-craven-908bb212/"
        ]
      }
    </script>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/blogs.html.erb
<%= render 'shared/navbar2' %>
<div class="blogs-wrapper">
  <a class="twitter-timeline" data-width="500" data-height="700" data-theme="dark" data-link-color="#A3C1AD" href="https://twitter.com/CravenPartners?ref_src=twsrc%5Etfw">Tweets by CravenPartners</a>
  <div class="blog">
    <div class="blogs-title">
      <h1>My Posts</h1>
    </div>
    <div class="blog-wrapper">
      <div class="blogs-main">
        <%#= render 'shared/blogs' %>
      </div>
    </div>
  </div>
</div>

<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<% if Date.today < "30-05-2020".to_date %>
<div id="covid">
  <h3>COVID Notice</h3>
  <p>Due to coronavirus I am offering my clients a range of new services to bring my talks to your audience remotely.</p>
  <p>Live and pre-recorded;</p>

    <ul>
      <li>Talks</li>
      <li>Webinars</li>
      <li>Coaching</li>
    </ul>  </div>
</div>
<% end %>

<div id="about"></div>

<%= render 'shared/about' %>

<%= render 'shared/video' %>

<%= render 'shared/talks' %>

<%= render 'shared/testimonial' %>

<%= render 'shared/clients' %>

<%= render 'shared/coaching' %>

<%= render 'shared/contact' %>

app/views/shared/_about.html.erb
<div class="description-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="about-title" itemscope>
        <h2 data-aos="fade-left" data-aos-duration="2000" itemprop='name'>Paul Craven - Behavioural Economics Expert</h2>
        <p>I help clients enhance their communication, decision-making and sales skills, using behavioural economics and psychology. My favourite definition of Behavioural Economics is “how real people make real decisions in the real world.” We all make mental short-cuts. Our minds play tricks.</p>
        <p>I give over 50 talks a year around the world. These include keynote conference speeches and internal team training. My audiences and clients range from investors to doctors to lawyers to entrepreneurs.</p>
      </div>
      <div class="sparks-content">

       <ul>
        <h4>A brief history</h4>
         <li><p>1983 - 1986 <span></span>: Cambridge University</p></li>
         <li><p>1986 - 2003 <span></span>: Schroders</p></li>
         <li><p>2003 - 2007 <span></span>: PIMCO</p></li>
         <li><p>2007 - 2013 <span></span>: Goldman Sachs</p></li>
         <li><p>2014 - present : Paul Craven Partners Ltd</p></li>
       </ul>

     </div>
     <div class="bio text-center" itemscope>
      <p>Take a few seconds to look at this extraordinary illusion which is the basis of the logo for Paul Craven Partners Ltd</p>
      <%= image_tag("jastrow.gif", class: "jastrow", itemprop: 'image', alt: "jastrow gif") %>
    </div>
  </div>
</div>
</div>

app/views/shared/_banner.html.erb
<%= render 'shared/contact-modal' %>
<div id="home" class="second-banner">
  <div id="carousel-example-generic2" class="carousel slide banner carousel-fade" data-ride="carousel" data-interval="5000" data-pause="null">
    <div class="carousel-inner" role="listbox">
      <div class="item active banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_url('main-1.jpg') %>)">
      </div>
      <div class="item banner banner2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_url('main-2.jpg') %>)">
      </div>
    </div>
  </div>
  <%= render 'shared/navbar' %>
  <div class="banner-content" itemscope>
    <h1 itemprop="name">Paul Craven</h1>
    <%= link_to "#about" do %>
      <h4 id="behav" itemprop="jobTitle">Behavioural Economics Expert</h4>
    <% end %>
    <%= link_to "#talks" do %>
      <h4 itemprop="hasOccupation">Professional Speaker</h4>
    <% end %>
    <%= link_to "#coaching" do %>
      <h4 itemprop="hasOccupation">Masterclass Coach</h4>
    <% end %>
    <button class="book-btn-green" data-bs-toggle="modal" data-bs-target="#myModal">Contact Me</button>
    <div class="head-test">
      <div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel" data-interval="6000" data-pause="null">
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <p>"<em>Paul is an accomplished presenter who never disappoints and if you need someone to speak or coach on Behavioural Economics, I cannot recommend him highly enough.</em>”</p>
            <p><em class="small-text">Frank Dolan, Chartered FCSI Partner & Chartered Wealth Manager Laurence Milbrook & Co</em></p>
          </div>
          <div class="item">
            <p>"<em>He has the rare ability to both entertain and educate, making the audience question previously held assumptions.</em>"</p>
            <p><em class="small-text">Alex Beveridge, Director the European Investor Institute</em></p>
          </div>
          <div class="item">
            <p>"<em>Paul has an all-too-rare mixture of erudition, wit and practical ideas.</em>"</p>
            <p><em class="small-text">Rory Sutherland - Vice Chairman, Ogilvy & Mather UK</em></p>
          </div>
        </div>
      </div>
    </div>
    <!-- Wrapper for slides -->
  </div>
</div>
<div class="arrow-container">
  <a href="#about">
    <div class="down-arrow">
      <i class="fa fa-angle-down"></i>
    </div>
  </a>
</div>
</div>

app/views/shared/_blogs.html.erb
<% @blogs.each_with_index do |article, index1| %>
<div class="row blog-row">
  <div class='col-xs-12 col-sm-6 blog-card'>
    <div class="blog-image" style="background-image: url('<%= article[:image] %>')">
    </div>
  </div>
  <div class='col-xs-12 col-sm-6 blog-card-det'>
    <div class="blog-title">
      <a href='<%= article[:link] %>' target="_blank"><h3><strong><%= article[:title] %></strong></h3></a>
    </div>
    <div class="blog-detail">
      <small><p style=”margin-top:-10px”> <%= article[:date].strftime('Published: %F') %> | <a href='<%= article[:link] %>'><em>Source: Medium - Paul Craven</em></a></a></p></small>
    </div>
    <div class="blog-description">
      <p><%= article[:description] %></p>
    </div>
    <a class="read-link" data-toggle="collapse" href="#collapseExample<%= index1 %>" aria-expanded="false" aria-controls="collapseExample<%= index1 %>">
      Read
    </a>
  </div>
</div>
<div class="collapse" id="collapseExample<%= index1 %>">
  <div class="blog-content">
    <%= raw article[:content] %>
  </div>
</div>
<% end %>

app/views/shared/_clients.html.erb
<div class="clients-wrapper">
  <div class="clients-title">
    <h2 data-aos="fade-left" data-aos-duration="2000">My Clients Include</h2>
  </div>
  <div class="clients-container" itemscope>
    <div class="client-layers">
      <div class="client-image"><%= cl_image_tag("paul-craven/1515008681366.png", alt: "national grid logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/Abingworth-logo_2x.png", alt: "Abingworth logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/accenture-logo.png.png", alt: "accenture logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/animated-logos.png", alt: "animated-logos", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/AXA.png", alt: "AXA", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/barnett-waddingham.png", alt: "barnett waddingham logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/BlackRock-white-logo.png", alt: "BlackRock logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/bnp-paribas-fortis.png", alt: "bnp paribas logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
    </div>
    <div class="client-layers">
      <div class="client-image"><%= cl_image_tag("paul-craven/cisilogo.png", alt: "cisi logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/Coutts-logo.png", alt: "Coutts logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/facebook.png", alt: "facebook logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/hymans_robertson_white.png", alt: "hymans robertson logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/lbs-logo.png", alt: "lbs logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/Lloyds-bank.png", alt: "Lloyds bank logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/mercer.png", alt: "mercer logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/nationwide-logo-offwhite.png", alt: "nationwide logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
    </div>
    <div class="client-layers">
      <div class="client-image"><%= cl_image_tag("paul-craven/nhs-logo.png", alt: "nhs logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/ogilvy-logo-white-event-app.png", alt: "ogilvy logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/old-mutual-wealth-private-client-advisers_white.png", alt: "old mutual wealth logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/rathbones_logo.png", alt: "rathbones logo", quality: "auto:eco", width: 115, itemprop: "image")%></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/statprologo2.png", alt: "statpro logo", quality: "auto:eco", width: 115, itemprop: "image")%></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/ubs-3.png", alt: "ubs logo", quality: "auto:eco", width: 115, itemprop: "image")%></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/willis_logo.png", alt: "willis logo", quality: "auto:eco", width: 115, itemprop: "image")%></div>
      <div class="client-image"><%= cl_image_tag("paul-craven/zurich-insurance-group_416x416.png", alt: "zurich insurance logo", quality: "auto:eco", width: 115, itemprop: "image") %></div>
    </div>
  </div>
</div>

app/views/shared/_coaching.html.erb
<div id="myGroup" class="description-wrapper">
  <div id="coaching" class="container-fluid">
    <div class="row justify-content-center">
      <div class="about-title">
        <h2 data-aos="fade-left" data-aos-duration="2000" id="talks">The Masterclass - Performance enhancement through behavioural insights</h2>
      </div>
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <div>
          <div class="sparks-content text-center">
            <p>The Masterclass teaches the rare application of behavioural methodology to the world of business, improving and enhancing your sales and communication techniques with prospects and clients.</p>
            <!-- <p>Every top sports team use coaches, as does nearly every top-class performer, whether in fields as wide-ranging as chess, classical music or the performing arts. Why is coaching so encouraged and welcomed in other performance-related professions, yet rare in business? Thankfully this outdated view is changing as corporate leaders recognise that their skills can indeed be enhanced.</p> -->
            <div class="masterclass-detail">
              <div>
                <p>The Masterclass is based upon a combination of three things: my 30 years of sales and marketing experience with Schroders, PIMCO and Goldman Sachs (successes and mistakes!), my love of behavioural economics and psychology, as well as my interest in helping take ideas and people from good to great.</p>
              </div>
              <div>
                <p>My ‘value-added’ comes in improving and enhancing your team's spoken and written sales communication with prospects and clients.</p>
              </div>
              <div>
                <p>Every Masterclass is bespoke to the client but there are three areas on which I typically focus, from a behavioural and psychological perspective.</p>
                <ol>
                  <li>
                    <p>Improving Sales Skills</p>
                  </li>
                  <li>
                    <p>Enhancing Presentations</p>
                  </li>
                  <li>
                    <p>Building Client Relationships</p>
                  </li>
                </ol>
              </div>
              <p>Whereas Masterclasses are suitable for small or large teams, I also offer training for individuals. My 1 to 1 personalised coaching course is designed to improve your confidence and skill relating to presentations and public speaking. </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--   <div>
    <ul class="nav nav-tabs talk-tabs" role="tablist">
      <li role="presentation" class="talk-tab"><a href="#masterclass2" aria-controls="masterclass2" role="tab" data-toggle="collapse" aria-expanded="false">The Masterclass</a></li> -->
  <!-- <li role="presentation" class="talk-tab"><a href="#intro" aria-controls="intro" role="tab" data-toggle="collapse" aria-expanded="false">1 to 1</a></li> -->
  <!--     </ul>
    <div class="container-fluid">
      <div class="row">
        <div class="tab-content col-xs-12 col-sm-8 col-sm-offset-2">
          <div role="tabpanel" class="collapse" id="masterclass2">
            <div class="masterclass-title text-center">
              <h3>The Masterclass (Full Day)</h3>
              <h4>Improving and enhancing your sales and communication techniques with prospects and clients</h4>
            </div>
            <div class="masterclass-detail">
              <div>
                <p>The Masterclass is based upon a combination of three things: my 30 years of sales and marketing experience with Schroders, PIMCO and Goldman Sachs (successes and mistakes!), my love of behavioural economics and psychology, as well as my interest in helping take ideas and people from good to great.</p>
              </div>
              <div>
                <p>My ‘value-added’ comes in improving and enhancing your team's spoken and written sales communication with prospects and clients.</p>
              </div>
              <div>
                <p>Every Masterclass is bespoke to the client but there are three areas on which I typically focus, from a behavioural and psychological perspective.</p>
                <ol>
                  <li><p>Improving Sales Skills</p></li>
                  <li><p>Enhancing Presentations</p></li>
                  <li><p>Building Client Relationships</p></li>
                </ol>
              </div>
              <p>Whereas Masterclasses are suitable for small or large teams, I also offer training for individuals. My 1 to 1 personalised coaching course is designed to improve your confidence and skill relating to presentations and public speaking. </p>
            </div>
          </div> -->
  <!-- <div role="tabpanel" class="collapse" id="intro">
          <div class="masterclass-title text-center">
            <h3>1 to 1</h3>
            <p>I offer 1 to 1 personalised coaching, to improve your confidence and skill, relating to presentations and public speaking.</p>
          </div>
        </div>
      </div> -->
  <!--     </div>
  </div>
</div> -->
  <div class="talk-photo" style="background-image: url(<%= image_url("paul-1.jpg") %>)">
  </div>
</div>

app/views/shared/_contact-modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <%# <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> %>
        <h1 class="modal-title fs-5" id="myModalLabel">How can I help?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: :message, url: "/message") do |f| %>
          <%= f.input :name, label: false, placeholder: "Your Name", required: true %>
          <%= f.input :email, label: false, placeholder: "Email", required: true %>
          <%= f.input :phone_number, label: false, placeholder: "Contact Number", required: true %>
          <!-- <p class="hidden-md form-date">Event Date</p> -->
          <%#= f.input :date, as: :string, input_html: { class: 'datepicker' }, label: false, placeholder: "Event Date", required: true %>
          <%= f.input :body, label: false, as: :text,  placeholder: "Message for Paul", required: true %>
          <%= f.button :submit, "Send", class: 'send-button', id: "button2" %>
          <%#= recaptcha_tags %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">

    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">

    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-sparks navbar fixed-top">
  <!-- Logo -->
  <%= link_to root_path do %>
    <%= image_tag "logo.png", class: "navbar-sparks-brand", style: "height: 110px", alt: "paul craven logo" %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-sparks-right d-none d-lg-block">
    <!-- Links -->
    <%= link_to "Home", "#home", class: "navbar-sparks-item navbar-sparks-link"%>
    <%= link_to "About", "#about", class: "navbar-sparks-item navbar-sparks-link"%>
    <%= link_to "Videos", "#videos", class: "navbar-sparks-item navbar-sparks-link"%>
    <%= link_to "Speaking", "#talks", class: "navbar-sparks-item navbar-sparks-link" %>
    <%= link_to "My Clients", "#testimonial", class: "navbar-sparks-item navbar-sparks-link" %>
    <%= link_to "Masterclass", "#coaching", class: "navbar-sparks-item navbar-sparks-link" %>
    <% link_to "Insights", blogs_path, class: "navbar-sparks-item navbar-sparks-link"  %>
    <a href="https://twitter.com/cravenpartners" target="_blank"><i class="fab fa-x-twitter"></i></a>
    <%= link_to "Contact", "#contact", class: "navbar-sparks-item navbar-sparks-link" %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-sparks-item d-lg-none">
    <div class="dropdown">
      <i class="fa fa-bars" type="button" data-bs-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-end navbar-sparks-dropdown-menu">
        <li><a class="dropdown-item" href="#home">Home</a></li>
        <li><a class="dropdown-item" href="#about">About</a></li>
        <li><a class="dropdown-item" href="#videos">Videos</a></li>
        <li><a class="dropdown-item" href="#talks">Speaking</a></li>
        <li><a class="dropdown-item" href="#testimonial">My Clients</a></li>
        <li><a class="dropdown-item" href="#coaching">Masterclass</a></li>
        <li><a class="dropdown-item" href="/blogs">Insights</a></li>
        <li><a class="dropdown-item" href="https://twitter.com/cravenpartners" target="_blank"><i class="fab fa-x-twitter"></i></a></li>
        <li><a class="dropdown-item" href="#contact">Contact</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar-sparks2 navbar fixed-top">
  <!-- Logo -->
  <%= link_to root_path do %>
    <%= image_tag "logo.png", class: "navbar-sparks-brand" %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-sparks-right hidden-xs hidden-sm">
    <!-- Links -->
    <%= link_to "Home", root_path, class: "navbar-sparks-item navbar-sparks-link"%>
    <%#= link_to "About", "/#about", class: "navbar-sparks-item navbar-sparks-link"%>
    <%#= link_to "Videos", root_url(anchor: "videos"), class: "navbar-sparks-item navbar-sparks-link"%>
    <%#= link_to "Talks", root_path(anchor: "talks"), class: "navbar-sparks-item navbar-sparks-link" %>
    <%#= link_to "Coaching", root_path(anchor: "coaching"), class: "navbar-sparks-item navbar-sparks-link" %>
    <%#= link_to "Testimonials", root_path(anchor: "testimonial"), class: "navbar-sparks-item navbar-sparks-link" %>
    <%#= link_to "Contact", root_path(anchor: "contact"), class: "navbar-sparks-item navbar-sparks-link" %>
    <%#= link_to "Blogs", blogs_path, class: "navbar-sparks-item navbar-sparks-link"  %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-sparks-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-sparks-dropdown-menu">
        <li><a href="#home">Home</a></li>
        <!--         <li><a href="#about">About</a></li>
        <li><a href="#videos">Videos</a></li>
        <li><a href="#talks">Talks</a></li>
        <li><a href="#coaching">Coaching</a></li>
        <li><a href="#testimonial">Testimonials</a></li>
        <li><a href="#contact">Contact</a></li> -->
      </ul>
    </div>
  </div>
</div>